#!/bin/sh
revealup serve slides.md \
    --template share/templates/slide.html.mt \
    --theme simple.css \
    --transition none \
    #--width 1024 --height 768
    #--width 1920 --height 1080
    --width 1440 --height 900
